import React, { createContext, useContext, useState } from 'react';

export type ThemeType = 'light' | 'dark' | 'ocean' | 'forest' | 'neon' | 'pastel' | 'volcano' | 'galaxy' | 'firefly' | 'lava' | 'candy' | 'mint' | 'royal' | 'sunset' | 'arctic' | 'desert' | 'jungle' | 'cosmic' | 'retro' | 'cyber' | 'autumn' | 'spring';

interface ThemeContextType {
    theme: ThemeType;
    setTheme: (theme: ThemeType) => void;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const themes = {
  light: {
    name: 'Light',
    icon: '☀️',
    primary: 'from-blue-500 to-blue-600',
    secondary: 'from-gray-50 to-gray-100',
    hover: 'hover:bg-gray-100',
    text: 'text-gray-800',
    mutedText: 'text-gray-600',
    border: 'border-gray-200',
    bg: 'bg-white',
    input: 'bg-gray-50',
    accent: 'blue',
    messageGlow: 'shadow-sm',
    selfMessage: 'bg-blue-500',
    otherMessage: 'bg-gray-100',
    sidebarHover: 'hover:bg-gray-100',
    messageText: 'text-gray-800',
    messageTextSelf: 'text-white',
    searchBg: 'bg-gray-100',
    searchText: 'text-gray-800',
    searchPlaceholder: 'placeholder-gray-500',
    divider: 'border-gray-200',
    activeItem: 'bg-gray-100',
    buttonHover: 'hover:bg-gray-200',
    iconColor: 'text-gray-700',
    headerText: 'text-gray-900',
    subText: 'text-gray-600',
    tooltipBg: 'bg-gray-800',
    tooltipText: 'text-white',
    border2: 'border-gray-200',
  },
  dark: {
    name: 'Dark',
    icon: '🌙',
    primary: 'from-gray-700 to-gray-800',
    secondary: 'from-gray-800 to-gray-900',
    hover: 'hover:bg-gray-700',
    text: 'text-white',
    mutedText: 'text-gray-400',
    border: 'border-gray-700',
    bg: 'bg-black',
    input: 'bg-gray-800',
    accent: 'gray', // Adjust this based on your accent preference if needed
    messageGlow: 'shadow-[0_0_15px_rgba(255,255,255,0.1)]',
    selfMessage: 'bg-gray-700',
    otherMessage: 'bg-gray-800',
    sidebarHover: 'hover:bg-gray-700',
    messageText: 'text-white',
    messageTextSelf: 'text-white',
    searchBg: 'bg-gray-800',
    searchText: 'text-white',
    searchPlaceholder: 'placeholder-gray-500',
    divider: 'border-gray-700',
    activeItem: 'bg-gray-700',
    buttonHover: 'hover:bg-gray-600',
    iconColor: 'text-gray-300',
    headerText: 'text-white',
    subText: 'text-gray-400',
    tooltipBg: 'bg-gray-700',
    tooltipText: 'text-white',
    border2: 'border-zinc-800',
  },
  midnightOasis: {
    name: 'Midnight Oasis',
    icon: '🌌',
    primary: 'from-blue-700 to-teal-600',
    secondary: 'from-blue-900 to-teal-900',
    hover: 'hover:bg-blue-800/50',
    text: 'text-teal-200',
    mutedText: 'text-teal-400',
    border: 'border-teal-700',
    bg: 'bg-blue-950',
    input: 'bg-blue-900',
    accent: 'teal',
    messageGlow: 'shadow-[0_0_15px_rgba(54,178,190,0.1)]',
    selfMessage: 'bg-teal-600',
    otherMessage: 'bg-blue-900',
    sidebarHover: 'hover:bg-blue-900',
    messageText: 'text-teal-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-blue-900',
    searchText: 'text-teal-200',
    searchPlaceholder: 'placeholder-teal-400',
    divider: 'border-teal-800',
    activeItem: 'bg-blue-900',
    buttonHover: 'hover:bg-blue-800',
    iconColor: 'text-teal-400',
    headerText: 'text-teal-200',
    subText: 'text-teal-400',
    tooltipBg: 'bg-teal-700',
    tooltipText: 'text-teal-200',
  },

  // Theme: Ember Night
  emberNight: {
    name: 'Ember Night',
    icon: '🔥',
    primary: 'from-orange-600 to-red-500',
    secondary: 'from-orange-900 to-red-900',
    hover: 'hover:bg-orange-800/50',
    text: 'text-orange-100',
    mutedText: 'text-orange-300',
    border: 'border-orange-800',
    bg: 'bg-orange-950',
    input: 'bg-orange-900',
    accent: 'red',
    messageGlow: 'shadow-[0_0_15px_rgba(252,165,165,0.1)]',
    selfMessage: 'bg-red-600',
    otherMessage: 'bg-orange-900',
    sidebarHover: 'hover:bg-orange-900',
    messageText: 'text-orange-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-orange-900',
    searchText: 'text-orange-100',
    searchPlaceholder: 'placeholder-orange-400',
    divider: 'border-orange-800',
    activeItem: 'bg-orange-900',
    buttonHover: 'hover:bg-orange-800',
    iconColor: 'text-orange-300',
    headerText: 'text-orange-100',
    subText: 'text-orange-300',
    tooltipBg: 'bg-orange-800',
    tooltipText: 'text-orange-100',
  },
  // Theme: Moonlight Mist
  moonlightMist: {
    name: 'Moonlight Mist',
    icon: '🌙',
    primary: 'from-gray-700 to-blue-600',
    secondary: 'from-gray-900 to-blue-900',
    hover: 'hover:bg-gray-800/50',
    text: 'text-blue-200',
    mutedText: 'text-blue-400',
    border: 'border-blue-700',
    bg: 'bg-gray-950',
    input: 'bg-gray-900',
    accent: 'blue',
    messageGlow: 'shadow-[0_0_15px_rgba(74,144,226,0.1)]',
    selfMessage: 'bg-blue-600',
    otherMessage: 'bg-gray-900',
    sidebarHover: 'hover:bg-gray-900',
    messageText: 'text-blue-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-gray-900',
    searchText: 'text-blue-200',
    searchPlaceholder: 'placeholder-blue-400',
    divider: 'border-blue-800',
    activeItem: 'bg-gray-900',
    buttonHover: 'hover:bg-gray-800',
    iconColor: 'text-blue-300',
    headerText: 'text-blue-200',
    subText: 'text-blue-400',
    tooltipBg: 'bg-blue-800',
    tooltipText: 'text-blue-200',
  },

  // Theme: Forest Shadow
  forestShadow: {
    name: 'Forest Shadow',
    icon: '🌲',
    primary: 'from-green-700 to-emerald-600',
    secondary: 'from-green-900 to-emerald-900',
    hover: 'hover:bg-green-800/50',
    text: 'text-emerald-200',
    mutedText: 'text-emerald-400',
    border: 'border-emerald-700',
    bg: 'bg-green-950',
    input: 'bg-green-900',
    accent: 'emerald',
    messageGlow: 'shadow-[0_0_15px_rgba(16,185,129,0.1)]',
    selfMessage: 'bg-emerald-600',
    otherMessage: 'bg-green-900',
    sidebarHover: 'hover:bg-green-900',
    messageText: 'text-emerald-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-green-900',
    searchText: 'text-emerald-200',
    searchPlaceholder: 'placeholder-emerald-400',
    divider: 'border-emerald-800',
    activeItem: 'bg-green-900',
    buttonHover: 'hover:bg-green-800',
    iconColor: 'text-emerald-300',
    headerText: 'text-emerald-200',
    subText: 'text-emerald-400',
    tooltipBg: 'bg-emerald-800',
    tooltipText: 'text-emerald-200',
  },

  // Theme: Sapphire Night
  sapphireNight: {
    name: 'Sapphire Night',
    icon: '💎',
    primary: 'from-blue-800 to-indigo-700',
    secondary: 'from-blue-900 to-indigo-900',
    hover: 'hover:bg-blue-800/50',
    text: 'text-indigo-200',
    mutedText: 'text-indigo-400',
    border: 'border-indigo-700',
    bg: 'bg-blue-950',
    input: 'bg-blue-900',
    accent: 'indigo',
    messageGlow: 'shadow-[0_0_15px_rgba(67,56,202,0.1)]',
    selfMessage: 'bg-indigo-700',
    otherMessage: 'bg-blue-900',
    sidebarHover: 'hover:bg-blue-900',
    messageText: 'text-indigo-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-blue-900',
    searchText: 'text-indigo-200',
    searchPlaceholder: 'placeholder-indigo-400',
    divider: 'border-indigo-800',
    activeItem: 'bg-blue-900',
    buttonHover: 'hover:bg-blue-800',
    iconColor: 'text-indigo-300',
    headerText: 'text-indigo-200',
    subText: 'text-indigo-400',
    tooltipBg: 'bg-indigo-800',
    tooltipText: 'text-indigo-200',
  },

  // Theme: Crimson Dark
  crimsonDark: {
    name: 'Crimson Dark',
    icon: '🌹',
    primary: 'from-red-700 to-rose-600',
    secondary: 'from-red-900 to-rose-900',
    hover: 'hover:bg-red-800/50',
    text: 'text-rose-200',
    mutedText: 'text-rose-400',
    border: 'border-rose-700',
    bg: 'bg-red-950',
    input: 'bg-red-900',
    accent: 'rose',
    messageGlow: 'shadow-[0_0_15px_rgba(190,24,93,0.1)]',
    selfMessage: 'bg-rose-600',
    otherMessage: 'bg-red-900',
    sidebarHover: 'hover:bg-red-900',
    messageText: 'text-rose-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-red-900',
    searchText: 'text-rose-200',
    searchPlaceholder: 'placeholder-rose-400',
    divider: 'border-rose-800',
    activeItem: 'bg-red-900',
    buttonHover: 'hover:bg-red-800',
    iconColor: 'text-rose-300',
    headerText: 'text-rose-200',
    subText: 'text-rose-400',
    tooltipBg: 'bg-rose-800',
    tooltipText: 'text-rose-200',
  },

  // Theme: Velvet Dream
  velvetDream: {
    name: 'Velvet Dream',
    icon: '🌸',
    primary: 'from-purple-700 to-pink-600',
    secondary: 'from-purple-900 to-pink-900',
    hover: 'hover:bg-purple-800/50',
    text: 'text-pink-200',
    mutedText: 'text-pink-400',
    border: 'border-pink-700',
    bg: 'bg-purple-950',
    input: 'bg-purple-900',
    accent: 'pink',
    messageGlow: 'shadow-[0_0_15px_rgba(219,39,119,0.1)]',
    selfMessage: 'bg-pink-600',
    otherMessage: 'bg-purple-900',
    sidebarHover: 'hover:bg-purple-900',
    messageText: 'text-pink-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-purple-900',
    searchText: 'text-pink-200',
    searchPlaceholder: 'placeholder-pink-400',
    divider: 'border-pink-800',
    activeItem: 'bg-purple-900',
    buttonHover: 'hover:bg-purple-800',
    iconColor: 'text-pink-300',
    headerText: 'text-pink-200',
    subText: 'text-pink-400',
    tooltipBg: 'bg-pink-800',
    tooltipText: 'text-pink-200',
  },

  // Theme: Obsidian Void
  obsidianVoid: {
    name: 'Obsidian Void',
    icon: '🖤',
    primary: 'from-gray-800 to-black',
    secondary: 'from-gray-900 to-gray-950',
    hover: 'hover:bg-gray-800/50',
    text: 'text-gray-300',
    mutedText: 'text-gray-500',
    border: 'border-gray-800',
    bg: 'bg-black',
    input: 'bg-gray-900',
    accent: 'gray',
    messageGlow: 'shadow-[0_0_15px_rgba(100,100,100,0.1)]',
    selfMessage: 'bg-gray-700',
    otherMessage: 'bg-gray-900',
    sidebarHover: 'hover:bg-gray-900',
    messageText: 'text-gray-300',
    messageTextSelf: 'text-white',
    searchBg: 'bg-gray-900',
    searchText: 'text-gray-300',
    searchPlaceholder: 'placeholder-gray-500',
    divider: 'border-gray-800',
    activeItem: 'bg-gray-900',
    buttonHover: 'hover:bg-gray-800',
    iconColor: 'text-gray-400',
    headerText: 'text-gray-300',
    subText: 'text-gray-500',
    tooltipBg: 'bg-gray-800',
    tooltipText: 'text-gray-300',
  },

  // Theme: Cosmic Grape
  cosmicGrape: {
    name: 'Cosmic Grape',
    icon: '🍇',
    primary: 'from-purple-700 to-violet-600',
    secondary: 'from-purple-900 to-violet-900',
    hover: 'hover:bg-purple-800/50',
    text: 'text-violet-200',
    mutedText: 'text-violet-400',
    border: 'border-violet-700',
    bg: 'bg-purple-950',
    input: 'bg-purple-900',
    accent: 'violet',
    messageGlow: 'shadow-[0_0_15px_rgba(139,92,246,0.1)]',
    selfMessage: 'bg-violet-600',
    otherMessage: 'bg-purple-900',
    sidebarHover: 'hover:bg-purple-900',
    messageText: 'text-violet-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-purple-900',
    searchText: 'text-violet-200',
    searchPlaceholder: 'placeholder-violet-400',
    divider: 'border-violet-800',
    activeItem: 'bg-purple-900',
    buttonHover: 'hover:bg-purple-800',
    iconColor: 'text-violet-300',
    headerText: 'text-violet-200',
    subText: 'text-violet-400',
    tooltipBg: 'bg-violet-800',
    tooltipText: 'text-violet-200',
  },

  // Theme: Deep Aqua
  deepAqua: {
    name: 'Deep Aqua',
    icon: '💧',
    primary: 'from-teal-700 to-cyan-600',
    secondary: 'from-teal-900 to-cyan-900',
    hover: 'hover:bg-teal-800/50',
    text: 'text-cyan-200',
    mutedText: 'text-cyan-400',
    border: 'border-cyan-700',
    bg: 'bg-teal-950',
    input: 'bg-teal-900',
    accent: 'cyan',
    messageGlow: 'shadow-[0_0_15px_rgba(6,182,212,0.1)]',
    selfMessage: 'bg-cyan-600',
    otherMessage: 'bg-teal-900',
    sidebarHover: 'hover:bg-teal-900',
    messageText: 'text-cyan-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-teal-900',
    searchText: 'text-cyan-200',
    searchPlaceholder: 'placeholder-cyan-400',
    divider: 'border-cyan-800',
    activeItem: 'bg-teal-900',
    buttonHover: 'hover:bg-teal-800',
    iconColor: 'text-cyan-300',
    headerText: 'text-cyan-200',
    subText: 'text-cyan-400',
    tooltipBg: 'bg-cyan-800',
    tooltipText: 'text-cyan-200',
  },

  // Tiếp tục với nhiều theme khác nữa nếu bạn muốn thêm các tùy chọn tối khác.

  // Theme: Neon Noir
  neonNoir: {
    name: 'Neon Noir',
    icon: '🕶️',
    primary: 'from-pink-500 to-purple-400',
    secondary: 'from-pink-900 to-purple-900',
    hover: 'hover:bg-pink-800/50',
    text: 'text-pink-200',
    mutedText: 'text-pink-400',
    border: 'border-pink-700',
    bg: 'bg-pink-950',
    input: 'bg-pink-900',
    accent: 'purple',
    messageGlow: 'shadow-[0_0_15px_rgba(245,101,242,0.1)]',
    selfMessage: 'bg-purple-600',
    otherMessage: 'bg-pink-900',
    sidebarHover: 'hover:bg-pink-900',
    messageText: 'text-pink-200',
    messageTextSelf: 'text-white',
    searchBg: 'bg-pink-900',
    searchText: 'text-pink-200',
    searchPlaceholder: 'placeholder-pink-400',
    divider: 'border-pink-800',
    activeItem: 'bg-pink-900',
    buttonHover: 'hover:bg-pink-800',
    iconColor: 'text-pink-300',
    headerText: 'text-pink-200',
    subText: 'text-pink-400',
    tooltipBg: 'bg-pink-800',
    tooltipText: 'text-pink-200',
  },
  twilight: {
    name: 'Twilight',
    icon: '🌆',
    primary: 'from-indigo-600 to-purple-500',
    secondary: 'from-indigo-900 to-purple-900',
    hover: 'hover:bg-indigo-800/50',
    text: 'text-indigo-100',
    mutedText: 'text-indigo-300',
    border: 'border-indigo-800',
    bg: 'bg-indigo-950',
    input: 'bg-indigo-900',
    accent: 'purple',
    messageGlow: 'shadow-[0_0_15px_rgba(99,102,241,0.1)]',
    selfMessage: 'bg-purple-500',
    otherMessage: 'bg-indigo-900',
    sidebarHover: 'hover:bg-indigo-900',
    messageText: 'text-indigo-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-indigo-900',
    searchText: 'text-indigo-100',
    searchPlaceholder: 'placeholder-indigo-400',
    divider: 'border-indigo-800',
    activeItem: 'bg-indigo-900',
    buttonHover: 'hover:bg-indigo-800',
    iconColor: 'text-indigo-300',
    headerText: 'text-indigo-100',
    subText: 'text-indigo-300',
    tooltipBg: 'bg-indigo-800',
    tooltipText: 'text-indigo-100',
  },
  tropical: {
    name: 'Tropical',
    icon: '🌴',
    primary: 'from-green-500 to-teal-400',
    secondary: 'from-green-900 to-teal-900',
    hover: 'hover:bg-green-900/50',
    text: 'text-teal-100',
    mutedText: 'text-teal-300',
    border: 'border-teal-800',
    bg: 'bg-green-950',
    input: 'bg-green-900',
    accent: 'teal',
    messageGlow: 'shadow-[0_0_15px_rgba(45,212,191,0.1)]',
    selfMessage: 'bg-teal-500',
    otherMessage: 'bg-green-900',
    sidebarHover: 'hover:bg-green-900',
    messageText: 'text-teal-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-green-900',
    searchText: 'text-teal-100',
    searchPlaceholder: 'placeholder-teal-400',
    divider: 'border-teal-800',
    activeItem: 'bg-green-900',
    buttonHover: 'hover:bg-green-800',
    iconColor: 'text-teal-300',
    headerText: 'text-teal-100',
    subText: 'text-teal-300',
    tooltipBg: 'bg-teal-800',
    tooltipText: 'text-teal-100',
  },
  velvet: {
    name: 'Velvet',
    icon: '🟣',
    primary: 'from-purple-800 to-purple-900',
    secondary: 'from-purple-700 to-purple-800',
    hover: 'hover:bg-purple-800/50',
    text: 'text-purple-100',
    mutedText: 'text-purple-300',
    border: 'border-purple-800',
    bg: 'bg-purple-950',
    input: 'bg-purple-900',
    accent: 'purple',
    messageGlow: 'shadow-[0_0_15px_rgba(128,0,128,0.1)]',
    selfMessage: 'bg-purple-600',
    otherMessage: 'bg-purple-800',
    sidebarHover: 'hover:bg-purple-800',
    messageText: 'text-purple-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-purple-800',
    searchText: 'text-purple-100',
    searchPlaceholder: 'placeholder-purple-400',
    divider: 'border-purple-800',
    activeItem: 'bg-purple-800',
    buttonHover: 'hover:bg-purple-700',
    iconColor: 'text-purple-300',
    headerText: 'text-purple-100',
    subText: 'text-purple-300',
    tooltipBg: 'bg-purple-800',
    tooltipText: 'text-purple-100',
  },
  sapphire: {
    name: 'Sapphire',
    icon: '💎',
    primary: 'from-blue-700 to-blue-800',
    secondary: 'from-blue-800 to-blue-900',
    hover: 'hover:bg-blue-900/50',
    text: 'text-blue-100',
    mutedText: 'text-blue-300',
    border: 'border-blue-800',
    bg: 'bg-blue-950',
    input: 'bg-blue-900',
    accent: 'blue',
    messageGlow: 'shadow-[0_0_15px_rgba(30,58,138,0.1)]',
    selfMessage: 'bg-blue-700',
    otherMessage: 'bg-blue-800',
    sidebarHover: 'hover:bg-blue-800',
    messageText: 'text-blue-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-blue-800',
    searchText: 'text-blue-100',
    searchPlaceholder: 'placeholder-blue-400',
    divider: 'border-blue-800',
    activeItem: 'bg-blue-800',
    buttonHover: 'hover:bg-blue-700',
    iconColor: 'text-blue-300',
    headerText: 'text-blue-100',
    subText: 'text-blue-300',
    tooltipBg: 'bg-blue-800',
    tooltipText: 'text-blue-100',
  },
  glacier: {
    name: 'Glacier',
    icon: '❄️',
    primary: 'from-cyan-500 to-blue-500',
    secondary: 'from-cyan-800 to-blue-800',
    hover: 'hover:bg-cyan-800/50',
    text: 'text-cyan-100',
    mutedText: 'text-cyan-300',
    border: 'border-cyan-800',
    bg: 'bg-cyan-950',
    input: 'bg-cyan-900',
    accent: 'blue',
    messageGlow: 'shadow-[0_0_15px_rgba(6,182,212,0.1)]',
    selfMessage: 'bg-cyan-600',
    otherMessage: 'bg-cyan-800',
    sidebarHover: 'hover:bg-cyan-800',
    messageText: 'text-cyan-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-cyan-900',
    searchText: 'text-cyan-100',
    searchPlaceholder: 'placeholder-cyan-400',
    divider: 'border-cyan-800',
    activeItem: 'bg-cyan-800',
    buttonHover: 'hover:bg-cyan-700',
    iconColor: 'text-cyan-300',
    headerText: 'text-cyan-100',
    subText: 'text-cyan-300',
    tooltipBg: 'bg-cyan-800',
    tooltipText: 'text-cyan-100',
  },
  rainforest: {
    name: 'Rainforest',
    icon: '🍃',
    primary: 'from-lime-700 to-teal-800',
    secondary: 'from-lime-900 to-teal-950',
    hover: 'hover:bg-lime-800/50',
    text: 'text-lime-100',
    mutedText: 'text-lime-300',
    border: 'border-lime-800',
    bg: 'bg-teal-950',
    input: 'bg-lime-900',
    accent: 'green',
    messageGlow: 'shadow-[0_0_15px_rgba(67,160,71,0.1)]',
    selfMessage: 'bg-lime-600',
    otherMessage: 'bg-teal-800',
    sidebarHover: 'hover:bg-lime-800',
    messageText: 'text-lime-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-lime-900',
    searchText: 'text-lime-100',
    searchPlaceholder: 'placeholder-lime-400',
    divider: 'border-lime-800',
    activeItem: 'bg-teal-800',
    buttonHover: 'hover:bg-lime-700',
    iconColor: 'text-lime-300',
    headerText: 'text-lime-100',
    subText: 'text-lime-300',
    tooltipBg: 'bg-lime-800',
    tooltipText: 'text-lime-100',
  },
  mystic: {
    name: 'Mystic',
    icon: '🔮',
    primary: 'from-indigo-500 to-violet-600',
    secondary: 'from-indigo-900 to-violet-950',
    hover: 'hover:bg-indigo-800/50',
    text: 'text-indigo-100',
    mutedText: 'text-indigo-300',
    border: 'border-indigo-800',
    bg: 'bg-violet-950',
    input: 'bg-indigo-900',
    accent: 'violet',
    messageGlow: 'shadow-[0_0_15px_rgba(139,92,246,0.1)]',
    selfMessage: 'bg-violet-600',
    otherMessage: 'bg-indigo-900',
    sidebarHover: 'hover:bg-indigo-800',
    messageText: 'text-indigo-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-indigo-900',
    searchText: 'text-indigo-100',
    searchPlaceholder: 'placeholder-indigo-400',
    divider: 'border-indigo-800',
    activeItem: 'bg-violet-900',
    buttonHover: 'hover:bg-indigo-700',
    iconColor: 'text-indigo-300',
    headerText: 'text-indigo-100',
    subText: 'text-indigo-300',
    tooltipBg: 'bg-indigo-800',
    tooltipText: 'text-indigo-100',
  },
  citrus: {
    name: 'Citrus',
    icon: '🍊',
    primary: 'from-yellow-400 to-orange-500',
    secondary: 'from-yellow-900 to-orange-900',
    hover: 'hover:bg-yellow-800/50',
    text: 'text-yellow-100',
    mutedText: 'text-yellow-300',
    border: 'border-yellow-800',
    bg: 'bg-orange-950',
    input: 'bg-yellow-900',
    accent: 'orange',
    messageGlow: 'shadow-[0_0_15px_rgba(251,191,36,0.1)]',
    selfMessage: 'bg-yellow-600',
    otherMessage: 'bg-orange-800',
    sidebarHover: 'hover:bg-yellow-900',
    messageText: 'text-yellow-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-yellow-800',
    searchText: 'text-yellow-100',
    searchPlaceholder: 'placeholder-yellow-400',
    divider: 'border-yellow-800',
    activeItem: 'bg-orange-800',
    buttonHover: 'hover:bg-yellow-700',
    iconColor: 'text-yellow-300',
    headerText: 'text-yellow-100',
    subText: 'text-yellow-300',
    tooltipBg: 'bg-yellow-800',
    tooltipText: 'text-yellow-100',
  },
  abyss: {
    name: 'Abyss',
    icon: '🌊',
    primary: 'from-cyan-800 to-blue-900',
    secondary: 'from-blue-950 to-gray-950',
    hover: 'hover:bg-blue-900/50',
    text: 'text-cyan-100',
    mutedText: 'text-cyan-300',
    border: 'border-blue-800',
    bg: 'bg-gray-950',
    input: 'bg-blue-900',
    accent: 'cyan',
    messageGlow: 'shadow-[0_0_15px_rgba(3,105,161,0.1)]',
    selfMessage: 'bg-cyan-800',
    otherMessage: 'bg-gray-900',
    sidebarHover: 'hover:bg-cyan-900',
    messageText: 'text-cyan-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-cyan-900',
    searchText: 'text-cyan-100',
    searchPlaceholder: 'placeholder-cyan-400',
    divider: 'border-cyan-800',
    activeItem: 'bg-gray-900',
    buttonHover: 'hover:bg-blue-700',
    iconColor: 'text-cyan-300',
    headerText: 'text-cyan-100',
    subText: 'text-cyan-300',
    tooltipBg: 'bg-cyan-800',
    tooltipText: 'text-cyan-100',
  },
  emberGlow: {
    name: 'EmberGlow',
    icon: '🔥',
    primary: 'from-red-600 to-orange-700',
    secondary: 'from-red-800 to-orange-900',
    hover: 'hover:bg-red-700/50',
    text: 'text-red-100',
    mutedText: 'text-orange-300',
    border: 'border-orange-800',
    bg: 'bg-red-950',
    input: 'bg-red-900',
    accent: 'orange',
    messageGlow: 'shadow-[0_0_15px_rgba(255,69,0,0.1)]',
    selfMessage: 'bg-orange-600',
    otherMessage: 'bg-red-900',
    sidebarHover: 'hover:bg-orange-800',
    messageText: 'text-orange-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-orange-900',
    searchText: 'text-orange-100',
    searchPlaceholder: 'placeholder-red-400',
    divider: 'border-red-800',
    activeItem: 'bg-red-900',
    buttonHover: 'hover:bg-red-700',
    iconColor: 'text-orange-300',
    headerText: 'text-orange-100',
    subText: 'text-orange-300',
    tooltipBg: 'bg-orange-800',
    tooltipText: 'text-orange-100',
  },

  ocean: {
    name: 'Ocean',
    icon: '🌊',
    primary: 'from-blue-400 to-cyan-500',
    secondary: 'from-blue-900 to-cyan-900',
    hover: 'hover:bg-blue-900/50',
    text: 'text-blue-100',
    mutedText: 'text-blue-300',
    border: 'border-blue-800',
    bg: 'bg-blue-950',
    input: 'bg-blue-900',
    accent: 'cyan',
    messageGlow: 'shadow-[0_0_15px_rgba(34,211,238,0.1)]',
    selfMessage: 'bg-cyan-500',
    otherMessage: 'bg-blue-900',
    sidebarHover: 'hover:bg-blue-900',
    messageText: 'text-blue-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-blue-900',
    searchText: 'text-blue-100',
    searchPlaceholder: 'placeholder-blue-400',
    divider: 'border-blue-800',
    activeItem: 'bg-blue-900',
    buttonHover: 'hover:bg-blue-800',
    iconColor: 'text-blue-300',
    headerText: 'text-blue-100',
    subText: 'text-blue-300',
    tooltipBg: 'bg-blue-800',
    tooltipText: 'text-blue-100',
  },
  forest: {
    name: 'Forest',
    icon: '🌲',
    primary: 'from-green-600 to-emerald-500',
    secondary: 'from-green-900 to-emerald-900',
    hover: 'hover:bg-green-900/50',
    text: 'text-green-100',
    mutedText: 'text-green-300',
    border: 'border-green-800',
    bg: 'bg-green-950',
    input: 'bg-green-900',
    accent: 'emerald',
    messageGlow: 'shadow-[0_0_15px_rgba(16,185,129,0.1)]',
    selfMessage: 'bg-emerald-500',
    otherMessage: 'bg-green-900',
    sidebarHover: 'hover:bg-green-900',
    messageText: 'text-green-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-green-900',
    searchText: 'text-green-100',
    searchPlaceholder: 'placeholder-green-400',
    divider: 'border-green-800',
    activeItem: 'bg-green-900',
    buttonHover: 'hover:bg-green-800',
    iconColor: 'text-green-300',
    headerText: 'text-green-100',
    subText: 'text-green-300',
    tooltipBg: 'bg-green-800',
    tooltipText: 'text-green-100',
  },
  neon: {
    name: 'Neon',
    icon: '💫',
    primary: 'from-fuchsia-500 to-pink-500',
    secondary: 'from-fuchsia-900 to-pink-900',
    hover: 'hover:bg-fuchsia-900/50',
    text: 'text-fuchsia-100',
    mutedText: 'text-fuchsia-300',
    border: 'border-fuchsia-800',
    bg: 'bg-fuchsia-950',
    input: 'bg-fuchsia-900',
    accent: 'pink',
    messageGlow: 'shadow-[0_0_15px_rgba(236,72,153,0.1)]',
    selfMessage: 'bg-pink-500',
    otherMessage: 'bg-fuchsia-900',
    sidebarHover: 'hover:bg-fuchsia-900',
    messageText: 'text-fuchsia-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-fuchsia-900',
    searchText: 'text-fuchsia-100',
    searchPlaceholder: 'placeholder-fuchsia-400',
    divider: 'border-fuchsia-800',
    activeItem: 'bg-fuchsia-900',
    buttonHover: 'hover:bg-fuchsia-800',
    iconColor: 'text-fuchsia-300',
    headerText: 'text-fuchsia-100',
    subText: 'text-fuchsia-300',
    tooltipBg: 'bg-fuchsia-800',
    tooltipText: 'text-fuchsia-100',
  },
  pastel: {
    name: 'Pastel',
    icon: '🎨',
    primary: 'from-violet-400 to-purple-400',
    secondary: 'from-violet-900 to-purple-900',
    hover: 'hover:bg-violet-900/50',
    text: 'text-violet-100',
    mutedText: 'text-violet-300',
    border: 'border-violet-800',
    bg: 'bg-violet-950',
    input: 'bg-violet-900',
    accent: 'purple',
    messageGlow: 'shadow-[0_0_15px_rgba(167,139,250,0.1)]',
    selfMessage: 'bg-purple-400',
    otherMessage: 'bg-violet-900',
    sidebarHover: 'hover:bg-violet-900',
    messageText: 'text-violet-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-violet-900',
    searchText: 'text-violet-100',
    searchPlaceholder: 'placeholder-violet-400',
    divider: 'border-violet-800',
    activeItem: 'bg-violet-900',
    buttonHover: 'hover:bg-violet-800',
    iconColor: 'text-violet-300',
    headerText: 'text-violet-100',
    subText: 'text-violet-300',
    tooltipBg: 'bg-violet-800',
    tooltipText: 'text-violet-100',
  },
  volcano: {
    name: 'Volcano',
    icon: '🌋',
    primary: 'from-red-500 to-orange-500',
    secondary: 'from-red-900 to-orange-900',
    hover: 'hover:bg-red-900/50',
    text: 'text-red-100',
    mutedText: 'text-red-300',
    border: 'border-red-800',
    bg: 'bg-red-950',
    input: 'bg-red-900',
    accent: 'orange',
    messageGlow: 'shadow-[0_0_15px_rgba(249,115,22,0.1)]',
    selfMessage: 'bg-orange-500',
    otherMessage: 'bg-red-900',
    sidebarHover: 'hover:bg-red-900',
    messageText: 'text-red-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-red-900',
    searchText: 'text-red-100',
    searchPlaceholder: 'placeholder-red-400',
    divider: 'border-red-800',
    activeItem: 'bg-red-900',
    buttonHover: 'hover:bg-red-800',
    iconColor: 'text-red-300',
    headerText: 'text-red-100',
    subText: 'text-red-300',
    tooltipBg: 'bg-red-800',
    tooltipText: 'text-red-100',
  },
  galaxy: {
    name: 'Galaxy',
    icon: '🌌',
    primary: 'from-indigo-500 to-purple-500',
    secondary: 'from-indigo-900 to-purple-900',
    hover: 'hover:bg-indigo-900/50',
    text: 'text-indigo-100',
    mutedText: 'text-indigo-300',
    border: 'border-indigo-800',
    bg: 'bg-indigo-950',
    input: 'bg-indigo-900',
    accent: 'purple',
    messageGlow: 'shadow-[0_0_15px_rgba(99,102,241,0.1)]',
    selfMessage: 'bg-purple-500',
    otherMessage: 'bg-indigo-900',
    sidebarHover: 'hover:bg-indigo-900',
    messageText: 'text-indigo-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-indigo-900',
    searchText: 'text-indigo-100',
    searchPlaceholder: 'placeholder-indigo-400',
    divider: 'border-indigo-800',
    activeItem: 'bg-indigo-900',
    buttonHover: 'hover:bg-indigo-800',
    iconColor: 'text-indigo-300',
    headerText: 'text-indigo-100',
    subText: 'text-indigo-300',
    tooltipBg: 'bg-indigo-800',
    tooltipText: 'text-indigo-100',
  },
  firefly: {
    name: 'Firefly',
    icon: '✨',
    primary: 'from-yellow-400 to-lime-400',
    secondary: 'from-yellow-900 to-lime-900',
    hover: 'hover:bg-yellow-900/50',
    text: 'text-yellow-100',
    mutedText: 'text-yellow-300',
    border: 'border-yellow-800',
    bg: 'bg-yellow-950',
    input: 'bg-yellow-900',
    accent: 'lime',
    messageGlow: 'shadow-[0_0_15px_rgba(234,179,8,0.1)]',
    selfMessage: 'bg-lime-400',
    otherMessage: 'bg-yellow-900',
    sidebarHover: 'hover:bg-yellow-900',
    messageText: 'text-yellow-100',
    messageTextSelf: 'text-gray-900',
    searchBg: 'bg-yellow-900',
    searchText: 'text-yellow-100',
    searchPlaceholder: 'placeholder-yellow-400',
    divider: 'border-yellow-800',
    activeItem: 'bg-yellow-900',
    buttonHover: 'hover:bg-yellow-800',
    iconColor: 'text-yellow-300',
    headerText: 'text-yellow-100',
    subText: 'text-yellow-300',
    tooltipBg: 'bg-yellow-800',
    tooltipText: 'text-yellow-100',
  },
  lava: {
    name: 'Lava',
    icon: '🔥',
    primary: 'from-orange-500 to-red-500',
    secondary: 'from-orange-900 to-red-900',
    hover: 'hover:bg-orange-900/50',
    text: 'text-orange-100',
    mutedText: 'text-orange-300',
    border: 'border-orange-800',
    bg: 'bg-orange-950',
    input: 'bg-orange-900',
    accent: 'red',
    messageGlow: 'shadow-[0_0_15px_rgba(249,115,22,0.1)]',
    selfMessage: 'bg-red-500',
    otherMessage: 'bg-orange-900',
    sidebarHover: 'hover:bg-orange-900',
    messageText: 'text-orange-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-orange-900',
    searchText: 'text-orange-100',
    searchPlaceholder: 'placeholder-orange-400',
    divider: 'border-orange-800',
    activeItem: 'bg-orange-900',
    buttonHover: 'hover:bg-orange-800',
    iconColor: 'text-orange-300',
    headerText: 'text-orange-100',
    subText: 'text-orange-300',
    tooltipBg: 'bg-orange-800',
    tooltipText: 'text-orange-100',
  },
  candy: {
    name: 'Candy',
    icon: '🍬',
    primary: 'from-pink-400 to-rose-400',
    secondary: 'from-pink-900 to-rose-900',
    hover: 'hover:bg-pink-900/50',
    text: 'text-pink-100',
    mutedText: 'text-pink-300',
    border: 'border-pink-800',
    bg: 'bg-pink-950',
    input: 'bg-pink-900',
    accent: 'rose',
    messageGlow: 'shadow-[0_0_15px_rgba(244,63,94,0.1)]',
    selfMessage: 'bg-rose-400',
    otherMessage: 'bg-pink-900',
    sidebarHover: 'hover:bg-pink-900',
    messageText: 'text-pink-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-pink-900',
    searchText: 'text-pink-100',
    searchPlaceholder: 'placeholder-pink-400',
    divider: 'border-pink-800',
    activeItem: 'bg-pink-900',
    buttonHover: 'hover:bg-pink-800',
    iconColor: 'text-pink-300',
    headerText: 'text-pink-100',
    subText: 'text-pink-300',
    tooltipBg: 'bg-pink-800',
    tooltipText: 'text-pink-100',
  },
  mint: {
    name: 'Mint',
    icon: '🌿',
    primary: 'from-emerald-400 to-teal-400',
    secondary: 'from-emerald-900 to-teal-900',
    hover: 'hover:bg-emerald-900/50',
    text: 'text-emerald-100',
    mutedText: 'text-emerald-300',
    border: 'border-emerald-800',
    bg: 'bg-emerald-950',
    input: 'bg-emerald-900',
    accent: 'teal',
    messageGlow: 'shadow-[0_0_15px_rgba(20,184,166,0.1)]',
    selfMessage: 'bg-teal-400',
    otherMessage: 'bg-emerald-900',
    sidebarHover: 'hover:bg-emerald-900',
    messageText: 'text-emerald-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-emerald-900',
    searchText: 'text-emerald-100',
    searchPlaceholder: 'placeholder-emerald-400',
    divider: 'border-emerald-800',
    activeItem: 'bg-emerald-900',
    buttonHover: 'hover:bg-emerald-800',
    iconColor: 'text-emerald-300',
    headerText: 'text-emerald-100',
    subText: 'text-emerald-300',
    tooltipBg: 'bg-emerald-800',
    tooltipText: 'text-emerald-100',
  },
  royal: {
    name: 'Royal',
    icon: '👑',
    primary: 'from-purple-500 to-violet-500',
    secondary: 'from-purple-900 to-violet-900',
    hover: 'hover:bg-purple-900/50',
    text: 'text-purple-100',
    mutedText: 'text-purple-300',
    border: 'border-purple-800',
    bg: 'bg-purple-950',
    input: 'bg-purple-900',
    accent: 'violet',
    messageGlow: 'shadow-[0_0_15px_rgba(139,92,246,0.1)]',
    selfMessage: 'bg-violet-500',
    otherMessage: 'bg-purple-900',
    sidebarHover: 'hover:bg-purple-900',
    messageText: 'text-purple-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-purple-900',
    searchText: 'text-purple-100',
    searchPlaceholder: 'placeholder-purple-400',
    divider: 'border-purple-800',
    activeItem: 'bg-purple-900',
    buttonHover: 'hover:bg-purple-800',
    iconColor: 'text-purple-300',
    headerText: 'text-purple-100',
    subText: 'text-purple-300',
    tooltipBg: 'bg-purple-800',
    tooltipText: 'text-purple-100',
  },
  sunset: {
    name: 'Sunset',
    icon: '🌅',
    primary: 'from-amber-500 to-red-500',
    secondary: 'from-amber-900 to-red-900',
    hover: 'hover:bg-amber-900/50',
    text: 'text-amber-100',
    mutedText: 'text-amber-300',
    border: 'border-amber-800',
    bg: 'bg-amber-950',
    input: 'bg-amber-900',
    accent: 'red',
    messageGlow: 'shadow-[0_0_15px_rgba(245,158,11,0.1)]',
    selfMessage: 'bg-red-500',
    otherMessage: 'bg-amber-900',
    sidebarHover: 'hover:bg-amber-900',
    messageText: 'text-amber-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-amber-900',
    searchText: 'text-amber-100',
    searchPlaceholder: 'placeholder-amber-400',
    divider: 'border-amber-800',
    activeItem: 'bg-amber-900',
    buttonHover: 'hover:bg-amber-800',
    iconColor: 'text-amber-300',
    headerText: 'text-amber-100',
    subText: 'text-amber-300',
    tooltipBg: 'bg-amber-800',
    tooltipText: 'text-amber-100',
  },
  arctic: {
    name: 'Arctic',
    icon: '❄️',
    primary: 'from-cyan-400 to-sky-400',
    secondary: 'from-cyan-900 to-sky-900',
    hover: 'hover:bg-cyan-900/50',
    text: 'text-cyan-100',
    mutedText: 'text-cyan-300',
    border: 'border-cyan-800',
    bg: 'bg-cyan-950',
    input: 'bg-cyan-900',
    accent: 'sky',
    messageGlow: 'shadow-[0_0_15px_rgba(14,165,233,0.1)]',
    selfMessage: 'bg-sky-400',
    otherMessage: 'bg-cyan-900',
    sidebarHover: 'hover:bg-cyan-900',
    messageText: 'text-cyan-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-cyan-900',
    searchText: 'text-cyan-100',
    searchPlaceholder: 'placeholder-cyan-400',
    divider: 'border-cyan-800',
    activeItem: 'bg-cyan-900',
    buttonHover: 'hover:bg-cyan-800',
    iconColor: 'text-cyan-300',
    headerText: 'text-cyan-100',
    subText: 'text-cyan-300',
    tooltipBg: 'bg-cyan-800',
    tooltipText: 'text-cyan-100',
  },
  desert: {
    name: 'Desert',
    icon: '🏜️',
    primary: 'from-yellow-500 to-orange-500',
    secondary: 'from-yellow-900 to-orange-900',
    hover: 'hover:bg-yellow-900/50',
    text: 'text-yellow-100',
    mutedText: 'text-yellow-300',
    border: 'border-yellow-800',
    bg: 'bg-yellow-950',
    input: 'bg-yellow-900',
    accent: 'orange',
    messageGlow: 'shadow-[0_0_15px_rgba(234,179,8,0.1)]',
    selfMessage: 'bg-orange-500',
    otherMessage: 'bg-yellow-900',
    sidebarHover: 'hover:bg-yellow-900',
    messageText: 'text-yellow-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-yellow-900',
    searchText: 'text-yellow-100',
    searchPlaceholder: 'placeholder-yellow-400',
    divider: 'border-yellow-800',
    activeItem: 'bg-yellow-900',
    buttonHover: 'hover:bg-yellow-800',
    iconColor: 'text-yellow-300',
    headerText: 'text-yellow-100',
    subText: 'text-yellow-300',
    tooltipBg: 'bg-yellow-800',
    tooltipText: 'text-yellow-100',
  },
  jungle: {
    name: 'Jungle',
    icon: '🌴',
    primary: 'from-lime-500 to-green-500',
    secondary: 'from-lime-900 to-green-900',
    hover: 'hover:bg-lime-900/50',
    text: 'text-lime-100',
    mutedText: 'text-lime-300',
    border: 'border-lime-800',
    bg: 'bg-lime-950',
    input: 'bg-lime-900',
    accent: 'green',
    messageGlow: 'shadow-[0_0_15px_rgba(132,204,22,0.1)]',
    selfMessage: 'bg-green-500',
    otherMessage: 'bg-lime-900',
    sidebarHover: 'hover:bg-lime-900',
    messageText: 'text-lime-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-lime-900',
    searchText: 'text-lime-100',
    searchPlaceholder: 'placeholder-lime-400',
    divider: 'border-lime-800',
    activeItem: 'bg-lime-900',
    buttonHover: 'hover:bg-lime-800',
    iconColor: 'text-lime-300',
    headerText: 'text-lime-100',
    subText: 'text-lime-300',
    tooltipBg: 'bg-lime-800',
    tooltipText: 'text-lime-100',
  },
  cosmic: {
    name: 'Cosmic',
    icon: '🌠',
    primary: 'from-violet-500 to-fuchsia-500',
    secondary: 'from-violet-900 to-fuchsia-900',
    hover: 'hover:bg-violet-900/50',
    text: 'text-violet-100',
    mutedText: 'text-violet-300',
    border: 'border-violet-800',
    bg: 'bg-violet-950',
    input: 'bg-violet-900',
    accent: 'fuchsia',
    messageGlow: 'shadow-[0_0_15px_rgba(167,139,250,0.1)]',
    selfMessage: 'bg-fuchsia-500',
    otherMessage: 'bg-violet-900',
    sidebarHover: 'hover:bg-violet-900',
    messageText: 'text-violet-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-violet-900',
    searchText: 'text-violet-100',
    searchPlaceholder: 'placeholder-violet-400',
    divider: 'border-violet-800',
    activeItem: 'bg-violet-900',
    buttonHover: 'hover:bg-violet-800',
    iconColor: 'text-violet-300',
    headerText: 'text-violet-100',
    subText: 'text-violet-300',
    tooltipBg: 'bg-violet-800',
    tooltipText: 'text-violet-100',
  },
  retro: {
    name: 'Retro',
    icon: '📺',
    primary: 'from-rose-500 to-pink-500',
    secondary: 'from-rose-900 to-pink-900',
    hover: 'hover:bg-rose-900/50',
    text: 'text-rose-100',
    mutedText: 'text-rose-300',
    border: 'border-rose-800',
    bg: 'bg-rose-950',
    input: 'bg-rose-900',
    accent: 'pink',
    messageGlow: 'shadow-[0_0_15px_rgba(244,63,94,0.1)]',
    selfMessage: 'bg-pink-500',
    otherMessage: 'bg-rose-900',
    sidebarHover: 'hover:bg-rose-900',
    messageText: 'text-rose-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-rose-900',
    searchText: 'text-rose-100',
    searchPlaceholder: 'placeholder-rose-400',
    divider: 'border-rose-800',
    activeItem: 'bg-rose-900',
    buttonHover: 'hover:bg-rose-800',
    iconColor: 'text-rose-300',
    headerText: 'text-rose-100',
    subText: 'text-rose-300',
    tooltipBg: 'bg-rose-800',
    tooltipText: 'text-rose-100',
  },
  cyber: {
    name: 'Cyber',
    icon: '🤖',
    primary: 'from-sky-400 to-indigo-400',
    secondary: 'from-sky-900 to-indigo-900',
    hover: 'hover:bg-sky-900/50',
    text: 'text-sky-100',
    mutedText: 'text-sky-300',
    border: 'border-sky-800',
    bg: 'bg-sky-950',
    input: 'bg-sky-900',
    accent: 'indigo',
    messageGlow: 'shadow-[0_0_15px_rgba(14,165,233,0.1)]',
    selfMessage: 'bg-indigo-400',
    otherMessage: 'bg-sky-900',
    sidebarHover: 'hover:bg-sky-900',
    messageText: 'text-sky-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-sky-900',
    searchText: 'text-sky-100',
    searchPlaceholder: 'placeholder-sky-400',
    divider: 'border-sky-800',
    activeItem: 'bg-sky-900',
    buttonHover: 'hover:bg-sky-800',
    iconColor: 'text-sky-300',
    headerText: 'text-sky-100',
    subText: 'text-sky-300',
    tooltipBg: 'bg-sky-800',
    tooltipText: 'text-sky-100',
  },
  autumn: {
    name: 'Autumn',
    icon: '🍁',
    primary: 'from-orange-400 to-amber-400',
    secondary: 'from-orange-900 to-amber-900',
    hover: 'hover:bg-orange-900/50',
    text: 'text-orange-100',
    mutedText: 'text-orange-300',
    border: 'border-orange-800',
    bg: 'bg-orange-950',
    input: 'bg-orange-900',
    accent: 'amber',
    messageGlow: 'shadow-[0_0_15px_rgba(251,191,36,0.1)]',
    selfMessage: 'bg-amber-400',
    otherMessage: 'bg-orange-900',
    sidebarHover: 'hover:bg-orange-900',
    messageText: 'text-orange-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-orange-900',
    searchText: 'text-orange-100',
    searchPlaceholder: 'placeholder-orange-400',
    divider: 'border-orange-800',
    activeItem: 'bg-orange-900',
    buttonHover: 'hover:bg-orange-800',
    iconColor: 'text-orange-300',
    headerText: 'text-orange-100',
    subText: 'text-orange-300',
    tooltipBg: 'bg-orange-800',
    tooltipText: 'text-orange-100',
  },
  spring: {
    name: 'Spring',
    icon: '🌸',
    primary: 'from-pink-400 to-rose-400',
    secondary: 'from-pink-900 to-rose-900',
    hover: 'hover:bg-pink-900/50',
    text: 'text-pink-100',
    mutedText: 'text-pink-300',
    border: 'border-pink-800',
    bg: 'bg-pink-950',
    input: 'bg-pink-900',
    accent: 'rose',
    messageGlow: 'shadow-[0_0_15px_rgba(244,63,94,0.1)]',
    selfMessage: 'bg-rose-400',
    otherMessage: 'bg-pink-900',
    sidebarHover: 'hover:bg-pink-900',
    messageText: 'text-pink-100',
    messageTextSelf: 'text-white',
    searchBg: 'bg-pink-900',
    searchText: 'text-pink-100',
    searchPlaceholder: 'placeholder-pink-400',
    divider: 'border-pink-800',
    activeItem: 'bg-pink-900',
    buttonHover: 'hover:bg-pink-800',
    iconColor: 'text-pink-300',
    headerText: 'text-pink-100',
    subText: 'text-pink-300',
    tooltipBg: 'bg-pink-800',
    tooltipText: 'text-pink-100',
  },
};

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [theme, setTheme] = useState<ThemeType>('dark');

    return (
        <ThemeContext.Provider value={{ theme, setTheme }}>
            {children}
        </ThemeContext.Provider>
    );
};

export const useTheme = () => {
    const context = useContext(ThemeContext);
    if (context === undefined) {
        throw new Error('useTheme must be used within a ThemeProvider');
    }
    return { ...context, currentTheme: themes[context.theme] };
};